server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/flow}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        enable.idempotence: true
  jackson:
    locale: pt_BR
    time-zone: America/Sao_Paulo
    deserialization:
      accept-float-as-int: false
    parser:
      allow-numeric-leading-zeros: true

app:
  kafka:
    events-topic: flow.events.v1
  outbox:
    mode: worker # 'worker' | 'cdc'
    poll-interval-ms: 1000
  cors:
    origins: ${APP_CORS_ORIGINS:http://localhost:3000,http://localhost:3001}
  storage:
    s3:
      enabled: ${APP_S3_ENABLED:true}
      endpoint: ${APP_S3_ENDPOINT:http://localhost:9000}
      region: ${APP_S3_REGION:us-east-1}
      accessKey: ${APP_S3_ACCESS_KEY:minioadmin}
      secretKey: ${APP_S3_SECRET_KEY:minioadmin}
      bucket: ${APP_S3_BUCKET:flow-files}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
